### ISSUE TITLE
Under windows not work import from jar (org.webjars/bootstrap) file.

### ISSUE THREAD

**Issue by zoos** [Deraen/boot-less#7]
Under linux work fine.

Log:

Compiling {less}... 1 changed files.
importing bootstrap/less/bootstrap.less at C:\Users\user\.boot\cache\tmp\Users\user\Projects\reactives\uc\rcesf6
Could not compile less. 1 error(s) occurred:
ERROR file:/C:/Users/user/.boot/cache/tmp/Users/user/Projects/reactives/uc/rcesf6/reactives.main.less 1:1 The file bootstrap/less/bootstrap.less does not exist.
 1: @import "bootstrap/less/bootstrap.less";
 2:

**Comment by Deraen** [comment]
Deraen/less4clj#4
